# Berlin Crypto event blog
# Using Evento Theme/Blog
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Berlin Crypto
logo: logo.png

#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Event

description: > # this means to ignore newlines until "baseurl:"
  Berlin Crypto Community

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://berlin-crypto.github.io" # the base hostname & protocol for your site

#These settings might be able to go?
author: Franziskus Kiefer
twitter_username: _franziskus_
github_username:  berlin-crypto

# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html

